## Exercise
## Equality

## Instructions
## - Write code to see if True equals False.
## - Check if -5 * 15 is not equal to 75.
## - Check if the strings "pyscript" and "PyScript" are equal.
## - Write code to see if True and 1 are equal.

## MY SOLUTION:

# Comparison of booleans
True==False

# Comparison of integers
-5*15!=75

# Comparison of strings
"pyscript"=="PyScript"

# Compare a boolean with an integer
True==1