## Exercise
## Line plot (1)

## Instructions
## - Print the last item from both the year and pop lists.
## - Import matplotlib.pyplot as plt.
## - Use plt.plot() to create a line plot with:
##     year on the horizontal axis
##     pop on the vertical axis
## - Finish with plt.show() to display the plot.

## MY SOLUTION:
'''
# Print the last item from year and pop
print(year)
print(pop)

# Import matplotlib.pyplot as plt
import matplotlib.pyplot as plt

# Make a line plot: year on the x-axis, pop on the y-axis
plt.plot(year,pop)

# Display the plot with plt.show()
plt.show()
'''