## Exercise
## Line plot (3)

## Instructions
## - Print the last item from both gdp_cap and life_exp.
## - Build a line chart with:
##     gdp_cap on the x-axis
##     life_exp on the y-axis
## - Finish with plt.show() to display the plot.

## MY SOLUTION:
'''
# Print the last item of gdp_cap and life_exp
print(life_exp)
print(gdp_cap)

# Make a line plot, gdp_cap on the x-axis, life_exp on the y-axis
plt.plot(gdp_cap,life_exp)

# Display the plot
plt.show()
'''